#!/bin/bash

# ===============================
# DAPATKAN IP DAN TANGGAL
# ===============================
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")


# ===============================
# AMBIL DATA CLIENT
# ===============================
MYIP=$ipsaya
url_izin="https://raw.githubusercontent.com/Pemulaajiw/v10/main/izin"
username=$(curl -sS $url_izin | grep $MYIP | awk '{print $2}')
valid=$(curl -sS $url_izin | grep $MYIP | awk '{print $3}')

echo "$username" >/usr/bin/user
echo "$valid" >/usr/bin/e
valid=$(cat /usr/bin/e)
username=$(cat /usr/bin/user)
# ===============================
# TANGGAL HARI INI DAN EXPIRY
# ===============================
today=$(date +'%Y-%m-%d')
Exp1="$valid"  # tanggal expiry
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
# ===============================
# FUNGSI HITUNG SELISIH HARI & FORMAT TANGGAL
# ===============================
datediff() {
    local d1=$(date -d "$1" +%s)
    local d2=$(date -d "$2" +%s)
    local diff=$(( (d1 - d2) / 86400 ))
    diff=${diff#-}  # selalu positif
    local formatted=$(date -d "$1" +'%d-%m-%Y')
    echo "$diff day | $formatted"
}

# ===============================
# CEK STATUS ACTIVE / EXPIRED
# ===============================
Info="(${green}Active${neutral})"
Error="(${r}Expired${neutral})"
if [[ "$today" < "$Exp1" ]]; then
    sts="${Info}"
else
    sts="${Error}"
fi

# Colors
green="\e[38;5;87m"
red="\e[38;5;196m"
neutral="\e[0m"
blue="\e[38;5;130m"
orange="\e[38;5;99m"
yellow="\e[38;5;226m"
purple="\e[38;5;141m"
bold_white="\e[1;37m"
reset="\e[0m"
pink="\e[38;5;205m"

# warna gelap
dark_gray="\e[38;5;240m"
dark_blue="\e[38;5;18m"
dark_red="\e[38;5;88m"
dark_green="\e[38;5;22m"
dark_orange="\e[38;5;94m"
dark_purple="\e[38;5;54m"
dark_cyan="\e[38;5;30m"
dark_blue_bg="\e[48;5;18m"

# warna terang
light_gray="\e[38;5;250m"
light_blue="\e[38;5;81m"
light_red="\e[38;5;210m"
light_green="\e[38;5;120m"
light_orange="\e[38;5;215m"
light_purple="\e[38;5;177m"
light_cyan="\e[38;5;159m"
light_yellow="\e[38;5;229m"

        # Function to count accounts
        count_accounts() {
            if [ ! -e "/etc/xray/$1/.$1.db" ]; then
                mkdir -p "/etc/xray/$1"
                touch "/etc/xray/$1/.$1.db"
            fi

            accounts=$(cat "/etc/xray/$1/.$1.db")
            if [[ $accounts = "" ]]; then
                echo "0"
            else
                cat "/etc/xray/$1/.$1.db" | grep "###" | wc -l
            fi
        }

        # Count accounts
        vm=$(count_accounts "vmess")
        vl=$(count_accounts "vless")
        tr=$(count_accounts "trojan")
        ss=$(count_accounts "shadowsocks")
        ssh=$(cat "/etc/ssh/.ssh.db" | grep "###" | wc -l)
        
        # Check service status
        cek_status() {
            status=$(systemctl is-active --quiet $1 && echo "aktif" || echo "nonaktif")
            if [ "$status" = "aktif" ]; then
                echo -e "${green}ON${neutral}"
            else
                echo -e "${red}OFF${neutral}"
            fi
        }

setup_bot_telegram() {
clear
echo -e "${orange}─────────────────────────────────────────${neutral}"
echo -e "${green}           SETUP BOT TELEGRAM         ${neutral}"
echo -e "${orange}─────────────────────────────────────────${neutral}"
echo -e ""
read -p "Masukkan token bot telegram Anda: " bot_token
read -p "Masukkan chat ID Anda: " chat_id
if [[ -z "$bot_token" || -z "$chat_id" ]]; then
echo -e "${red}Token bot atau chat ID tidak boleh kosong.${neutral}"
return
fi
if [ -f /root/.vars ]; then
rm -f /root/.vars
fi
echo "bot_token=\"$bot_token\"" >> /root/.vars
echo "telegram_id=\"$chat_id\"" >> /root/.vars
systemctl restart limitip > /dev/null 2>&1
echo -e "${dark_purple}─────────────────────────────────────────"
echo -e "${green}Token bot dan chat ID telah disimpan di /root/.vars${neutral}"
read -n 1 -s -r -p "Press any key to return to the menu"
}
      
            clear
            # Display menu
            display_menu() {
echo -e "${dark_blue_bg}${pink}              ☯ MERAUKE PROJECT TUNNELING ☯              ${neutral}"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mOS            \e[38;5;87m:  \e[38;5;141m"`hostnamectl | grep "Operating System" | cut -d ' ' -f5-`
echo -e "${orange} \e[38;5;196m• \e[38;5;226mIP            \e[38;5;87m:  \e[38;5;141m$(curl -s ipv4.icanhazip.com 2>/dev/null || echo "Unable to detect IP")"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mRAM           \e[38;5;87m:  \e[38;5;141m$(free -m | awk 'NR==2 {print $3 "MB / " $2 "MB"}')"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mISP           \e[38;5;87m:  \e[38;5;141m$(curl -s ipinfo.io/org 2>/dev/null | cut -d ' ' -f 2-100 || echo "Unable to detect ISP")"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mCITY          \e[38;5;87m:  \e[38;5;141m$(curl -s ipinfo.io/city 2>/dev/null || echo "Unable to detect city")"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mDOMAIN        \e[38;5;87m:  \e[38;5;141m$(head -n1 /etc/xray/domain 2>/dev/null || echo "No domain registered")"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mDATE & TIME   \e[38;5;87m:  \e[38;5;141m$(date -R | cut -d " " -f -5)"
echo -e "${orange} \e[38;5;196m• \e[38;5;226mUPTIME        \e[38;5;87m:  \e[38;5;141m$(uptime -p 2>/dev/null | cut -d ' ' -f 2-10000 || echo "Unable to detect uptime")"
echo -e "${dark_blue_bg}${pink}                   ☯ STATUS SERVICE ☯                    ${neutral}"
echo -e "    ${yellow}XRAY \e[38;5;87m: "$(cek_status vmess@config)"${yellow}   HAPROXY \e[38;5;87m: "$(cek_status haproxy)"${yellow}  SSHOVPN \e[38;5;87m: "$(cek_status ssh)" ${neutral}"
printf "\e[0m%-13s %-7s %-8s %2s\n" "[ACCOUNT]  :  SSH      VMESS       VLESS      TROJAN       SSWS         "
printf "\e[0m%-13s %-7s %-8s %2s\n" "[PREMIUM]  :  $ssh        $vm           $vl           $tr            $ss           "
echo -e "${dark_blue_bg}${pink}                   ☯ MENU AUTOSCRIPT ☯                   ${neutral}"
echo -e " ${orange}[$green 01 ${orange}] \e[38;5;226mSsh Menu        ${orange}[$green 05 ${orange}] \e[38;5;226mShdwscks Menu    ${neutral}"
echo -e " ${orange}[$green 02 ${orange}] \e[38;5;226mVmess Menu      ${orange}[$green 06 ${orange}] \e[38;5;226mNotif Bot Menu   ${neutral}"
echo -e " ${orange}[$green 03 ${orange}] \e[38;5;226mVless Menu      ${orange}[$green 07 ${orange}] \e[38;5;226mBot Telegram Menu${neutral}"
echo -e " ${orange}[$green 04 ${orange}] \e[38;5;226mTrojan Menu     ${orange}[$green 08 ${orange}] \e[38;5;226mSettings Menu    ${neutral}"
echo -e "${dark_blue_bg}                 ${pink}SCRIPT VERSION: V10.0 LTS                ${neutral}"
echo -e "                ${orange}───${green}───${yellow}───${blue}───${purple}───${red}───${neutral}"
echo -e " [\e[36m•x\e[0m] Exit Panel"
echo -e "${dark_blue_bg}${pink}                    ☯ OTHER DETAILS ☯                    ${neutral}"
echo -e "   ${red} • ${neutral}ID CLIENTS :  $username ${sts}"            
echo -e "   ${red} • ${neutral}SC EXPIRED :  $(datediff "$Exp1" "$today")"
echo -e " "
read -p "Pick a number (1-8) or hit 'x' to bail: " choice
    echo -e ""
    case $choice in
        1 | 01) menussh ;;
        2 | 02) menuvmess ;;
        3 | 03) menuvless ;;
        4 | 04) menutrojan ;;
        5 | 05) menushadowsocks ;;
        6 | 06) setup_bot_telegram ;;
        7 | 07) bot server ;;
        8 | 08) features ;;
        x | X)
            echo -e "${green}Thank you for using our service.${neutral}"
            exit 0
            ;;
        *)
            echo -e "${red}Invalid choice. Please try again.${neutral}"
            sleep 2
            display_menu
            ;;
    esac
}

# === CALL MENU ===
display_menu
